In [2]:
import pandas as pd
books = pd.read_csv("../datasets/books_text_classified.csv")
books

,BookID,FormattedBookID,Book,Author,Description,Genres,Avg_Rating,Num_Ratings,URL,Processed_Genres,Filtered_Genres,Mapped_Genre,Predicted_Genres,Predictions,id_desc
0,1,BK000001,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4.47,9278135,https://www.goodreads.com/book/show/72193.Harr...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...","['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",Fiction,Fiction,1,BK000001 Harry Potter thinks he is an ordinary...
1,2,BK000002,"Hungerspelen (The Hunger Games, #1)",Suzanne Collins,24 deltagare. Bara en överlever. Varje år dire...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/13616052-h...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Fiction,Fiction,1,BK000002 24 deltagare. Bara en överlever. Varj...
2,3,BK000003,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/12187803-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Fiction,Fiction,1,BK000003 Could you survive on your own in the ...
3,4,BK000004,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,In the ruins of a place once known as North Am...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/18626858-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Fiction,Nonfiction,0,BK000004 In the ruins of a place once known as...
4,5,BK000005,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,Sometime in the future after the destruction o...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/12091570-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",Fiction,Fiction,1,BK000005 Sometime in the future after the dest...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8840,9026,BK009026,"Mutantupproret 99,4% DNA",Martin J. Sallberg,En dystopisk framtidsskildring av en värld eft...,"['Science Fiction', 'Dystopia']",4.20,5,https://www.goodreads.com/book/show/29762076-m...,"['Science Fiction', 'Dystopia']","['Science Fiction', 'Dystopia']",Nonfiction,Fiction,0,BK009026 En dystopisk framtidsskildring av en ...
8841,9027,BK009027,The Future of Man: Extinction or Glory?,Peter Hollings,"In only a few generations, our species will ei...",['Science'],4.40,5,https://www.goodreads.com/book/show/6586918-th...,['Science'],['Science'],Nonfiction,Nonfiction,1,"BK009027 In only a few generations, our specie..."
8842,9030,BK009030,"The Stone Seekers (Dragon Hunters, #1)",L.L. Hansen,"In 1000 B.C., two 10-year-old boys, Zeth and C...","['Fantasy', 'Dragons']",4.00,4,https://www.goodreads.com/book/show/17259389-t...,"['Fantasy', 'Dragons']",['Fantasy'],Nonfiction,Nonfiction,1,"BK009030 In 1000 B.C., two 10-year-old boys, Z..."
8843,9033,BK009033,The Travels of Marco Polo,Giulio Einaudi,"Marco Polo, a Medieval Venetian, traveled thro...","['Travel', 'History']",3.00,4,https://www.goodreads.com/book/show/15790154-t...,"['Travel', 'History']",['History'],Nonfiction,Nonfiction,1,"BK009033 Marco Polo, a Medieval Venetian, trav..."
8844,9035,BK009035,The Water Walls,iLana Markarov,"One island, dangerous on the outside, surround...","['Fantasy', 'Adventure']",5.00,4,https://www.goodreads.com/book/show/61312854-t...,"['Fantasy', 'Adventure']","['Fantasy', 'Adventure']",Nonfiction,Fiction,0,"BK009035 One island, dangerous on the outside,..."

Model Used
#### https://huggingface.co/j-hartmann/emotion-english-distilroberta-base

In [3]:

from transformers import pipeline

pipe = pipeline("text-classification", 
                model="j-hartmann/emotion-english-distilroberta-base",
                top_k=None,
                device=0,
                truncation=True,                    
                max_length=512,                     
                truncation_strategy='longest_first' 
)

Device set to use cuda:0

In [4]:
pipe("Harry is a wizard with a demon")

[[{'label': 'disgust', 'score': 0.6851375699043274},
  {'label': 'fear', 'score': 0.14991424977779388},
  {'label': 'sadness', 'score': 0.07725250720977783},
  {'label': 'anger', 'score': 0.03583674505352974},
  {'label': 'neutral', 'score': 0.03370324522256851},
  {'label': 'surprise', 'score': 0.01685492694377899},
  {'label': 'joy', 'score': 0.0013007759116590023}]]

In [45]:
df = books[['FormattedBookID','Description']]

In [46]:
df

     FormattedBookID                                        Description
0           BK000001  Harry Potter thinks he is an ordinary boy - un...
1           BK000002  24 deltagare. Bara en överlever. Varje år dire...
2           BK000003  Could you survive on your own in the wild, wit...
3           BK000004  In the ruins of a place once known as North Am...
4           BK000005  Sometime in the future after the destruction o...
...              ...                                                ...
8840        BK009026  En dystopisk framtidsskildring av en värld eft...
8841        BK009027  In only a few generations, our species will ei...
8842        BK009030  In 1000 B.C., two 10-year-old boys, Zeth and C...
8843        BK009033  Marco Polo, a Medieval Venetian, traveled thro...
8844        BK009035  One island, dangerous on the outside, surround...

[8845 rows x 2 columns]

In [11]:
emotion_labels = ["anger","disgust","fear","joy","sadness","suprise","neutral"]

In [12]:
scores = pipe(df["Description"][0].split('.'))
scores

[[{'label': 'fear', 'score': 0.774424135684967},
  {'label': 'neutral', 'score': 0.09275589138269424},
  {'label': 'anger', 'score': 0.047540292143821716},
  {'label': 'joy', 'score': 0.026080481708049774},
  {'label': 'disgust', 'score': 0.023268844932317734},
  {'label': 'surprise', 'score': 0.019716668874025345},
  {'label': 'sadness', 'score': 0.01621369644999504}],
 [{'label': 'fear', 'score': 0.6197952628135681},
  {'label': 'anger', 'score': 0.1801619529724121},
  {'label': 'neutral', 'score': 0.09712021052837372},
  {'label': 'disgust', 'score': 0.05276859179139137},
  {'label': 'sadness', 'score': 0.035274770110845566},
  {'label': 'joy', 'score': 0.009936078451573849},
  {'label': 'surprise', 'score': 0.004943060223013163}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400667041540146},
  {'label': 'surprise', 'score': 0.07876553386449814},
  {'label': 'anger', 'score': 0.06413363665342331},
  {'label': 'fear', 'score': 0.051362816244363785},
  {'label': 'joy', 'score': 0.04056441783905029}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400667041540146},
  {'label': 'surprise', 'score': 0.07876553386449814},
  {'label': 'anger', 'score': 0.06413363665342331},
  {'label': 'fear', 'score': 0.051362816244363785},
  {'label': 'joy', 'score': 0.04056441783905029}],
 [{'label': 'surprise', 'score': 0.6870579123497009},
  {'label': 'neutral', 'score': 0.14405934512615204},
  {'label': 'anger', 'score': 0.07597929239273071},
  {'label': 'joy', 'score': 0.06516613811254501},
  {'label': 'sadness', 'score': 0.013541285879909992},
  {'label': 'disgust', 'score': 0.01155738066881895},
  {'label': 'fear', 'score': 0.002638653153553605}]]

In [13]:
for i in range(len(scores)):
    print(scores[i][0])

{'label': 'fear', 'score': 0.774424135684967}
{'label': 'fear', 'score': 0.6197952628135681}
{'label': 'neutral', 'score': 0.549476683139801}
{'label': 'neutral', 'score': 0.549476683139801}
{'label': 'surprise', 'score': 0.6870579123497009}

In [17]:
def calculate_max_scores(description):
    sentences = [s.strip() for s in description.split('.') if s.strip()]
    
    sentence_emotions = []
    for sentence in sentences:
        scores = pipe(sentence)
        max_emotion = max(scores[0], key=lambda x: x["score"])
        sentence_emotions.append([max_emotion['label'],max_emotion['score']])
    return max(sentence_emotions)
def calculate_max_scores(description):
    if not description or not isinstance(description, str) or not description.strip():
        return ['neutral', 0.0]  
    
    sentences = [s.strip() for s in description.split('.') if s.strip()]
    
    if not sentences:
        return ['neutral', 0.0]
    
    sentence_emotions = []
    for sentence in sentences:
        try:
            scores = pipe(sentence)
            
            # Check if scores list is empty
            if not scores or not scores[0]:
                continue
            
            max_emotion = max(scores[0], key=lambda x: x["score"])
            sentence_emotions.append([max_emotion['label'], max_emotion['score']])
        
        except Exception as e:
            print(f"Error processing sentence: {sentence}")
            print(f"Error details: {e}")
            continue
    
    if not sentence_emotions:
        return ['neutral', 0.0]
    
    return max(sentence_emotions, key=lambda x: x[1])

In [18]:
res = calculate_max_scores(df["Description"][2])
res

['neutral', 0.943543553352356]

In [19]:
from tqdm import tqdm
tqdm.pandas()
df["Emotion"] = df["Description"].progress_apply(calculate_max_scores)

100%|██████████| 8845/8845 [16:14<00:00,  9.07it/s]
C:\Users\ANAND REDDY\AppData\Local\Temp\ipykernel_14672\2510334420.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Emotion"] = df["Description"].progress_apply(calculate_max_scores)

In [ ]:
df['sentiment'] = df['Emotion'].apply(lambda x: x[0] if x else 'neutral')

In [5]:
df

,FormattedBookID,Description,Emotion,sentiment
0,BK000001,Harry Potter thinks he is an ordinary boy - un...,"['fear', 0.774424135684967]",fear
1,BK000002,24 deltagare. Bara en överlever. Varje år dire...,"['fear', 0.8872978687286377]",fear
2,BK000003,"Could you survive on your own in the wild, wit...","['neutral', 0.943543553352356]",neutral
3,BK000004,In the ruins of a place once known as North Am...,"['sadness', 0.7970337271690369]",sadness
4,BK000005,Sometime in the future after the destruction o...,"['neutral', 0.8030902743339539]",neutral
...,...,...,...,...
8840,BK009026,En dystopisk framtidsskildring av en värld eft...,"['neutral', 0.5866175293922424]",neutral
8841,BK009027,"In only a few generations, our species will ei...","['neutral', 0.966056227684021]",neutral
8842,BK009030,"In 1000 B.C., two 10-year-old boys, Zeth and C...","['fear', 0.8579759001731873]",fear
8843,BK009033,"Marco Polo, a Medieval Venetian, traveled thro...","['neutral', 0.9289608001708984]",neutral
8844,BK009035,"One island, dangerous on the outside, surround...","['fear', 0.8821620941162109]",fear

In [24]:
books = pd.merge(books,df,on="FormattedBookID")

In [4]:
data = books[["FormattedBookID","Mapped_Genre"]]
data

     FormattedBookID Mapped_Genre
0           BK000001      Fiction
1           BK000002      Fiction
2           BK000003      Fiction
3           BK000004      Fiction
4           BK000005      Fiction
...              ...          ...
8840        BK009026   Nonfiction
8841        BK009027   Nonfiction
8842        BK009030   Nonfiction
8843        BK009033   Nonfiction
8844        BK009035   Nonfiction

[8845 rows x 2 columns]

In [25]:
books.drop(["Predicted_Genres", "Processed_Genres","Predictions"], axis=1,inplace=True)

In [5]:
books.head()

,BookID,FormattedBookID,Book,Author,Description,Genres,Avg_Rating,Num_Ratings,URL,Filtered_Genres,Emotion,sentiment,Mapped_Genre,id_desc
0,1,BK000001,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4.47,9278135,https://www.goodreads.com/book/show/72193.Harr...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...","['fear', 0.774424135684967]",fear,Fiction,BK000001 Harry Potter thinks he is an ordinary...
1,2,BK000002,"Hungerspelen (The Hunger Games, #1)",Suzanne Collins,24 deltagare. Bara en överlever. Varje år dire...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/13616052-h...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['fear', 0.8872978687286377]",fear,Fiction,BK000002 24 deltagare. Bara en överlever. Varj...
2,3,BK000003,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/12187803-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['neutral', 0.943543553352356]",neutral,Fiction,BK000003 Could you survive on your own in the ...
3,4,BK000004,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,In the ruins of a place once known as North Am...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/18626858-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['sadness', 0.7970337271690369]",sadness,Fiction,BK000004 In the ruins of a place once known as...
4,5,BK000005,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,Sometime in the future after the destruction o...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,7963186,https://www.goodreads.com/book/show/12091570-t...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['neutral', 0.8030902743339539]",neutral,Fiction,BK000005 Sometime in the future after the dest...

In [6]:
books.to_csv("books_with_emotion.csv",index=False)